import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({children, }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    {/* 공통 wrapper */}
    <div className="min-h-screen flex justify-center">
      {/* 모바일/웹앱 고정 폭 */}
      <div className="w-[375px] bg-yellow min-h-screen overflow-x-hidden border rounded-xl shadow">
        {children}
      </div>
    </div>
    </body>
    </html>
  );
}